### DISCUSSION TITLE
Typical use question: Are `analyze` and `verify-policy` usually targeting the same component?

### DISCUSSION THREAD

**Discussion by jgsuess** [oracle/macaron#404] [Q&A] [answered]
Macaron seems to have two [execution phases](https://gitlab.com/committed-consulting/mde-devops/macaron-example/-/wikis/Anatomy-of-Macaron#execution-phases): `analyze` and `verify-policy`.

To model the configuration with a little more interesting detail, I would like to model these two calls. Now for me the question is: Would a typical user always analyze and verify the *same* component, or would it be common to analyze a component and then verify only on specific dependencies of that component.

I know that analyze may bring in the data for dependencies, so a verify call might turn up something useful. But I am not sure what a developers typical workflow would entail. I am talking about someone who is just an average user, not an expert in the configuration, as that is what I am building my case for.

To motivate what I am about to do: The calls below are using parameters for remote path, branch and commit. My goal is to extract them to the configuration model and then generate the shell call dynamically. And this prompts the question whether I need one or two sets of data for analyze and verify separately.

```yaml
run_macaron_analysis:
  extends: .run_macaron
  stage: execute_macaron_analysis
  script:
    - >-
      ${MACARON} analyze -rp
      https://github.com/micronaut-projects/micronaut-core -b 4.0.x -d
      82d115b4901d10226552ac67b0a10978cd5bc603

run_macaron_policy:
  extends: .run_macaron
  stage: execute_macaron_policy_check
  script:
    - >-
      ${MACARON} verify-policy -d ${OUTPUT_DIRECTORY}/macaron.db
      --file ${CI_PROJECT_DIR}/reference/oci-micronaut.dl
      || true
    - >-
      ${MACARON} verify-policy -d ${OUTPUT_DIRECTORY}/macaron.db
      --file ${CI_PROJECT_DIR}/target/Basic_mapstruct_mapstruct.dl
      || true
```
